# https://docs.github.com/en/actions/guides/publishing-nodejs-packages#publishing-packages-to-the-npm-registry
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsrun
# https://snyk.io/blog/github-actions-to-securely-publish-npm-packages/

name: Publish package to NPM

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build on Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install package dependencies
        working-directory: ${{ secrets.MAIN_FOLDER }}
        run: npm ci --ignore-scripts

      - name: Compile TS files to JS files
        working-directory: ${{ secrets.MAIN_FOLDER }}
        run: npm run build --if-present

      - name: Publish package to NPM
        working-directory: ${{ secrets.MAIN_FOLDER }}
        run: npm publish --ignore-scripts --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
