# NPM Publish
# @see https://github.com/marketplace/actions/npm-publish

name: NPM publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10

      - run: cd src && npm install
      - run: cd src && npm build

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./src/package.json

      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} to ${{ steps.publish.outputs.version }}"
